package utility;

public class Profile_Admin_Constant {
	
	public static final String CONFIG_FILEPATH="src/config_file/dataFile.properties";
	public static final String HOME_PAGE_FILEPATH="Profile_Admin_Page_Object_Repository/Home_Page.properties";
	public static final String CCR_SEARCH_PAGE_FILEPATH="Profile_Admin_Page_Object_Repository/CCR_Search_Page.properties";
	public static final String ADDUSERPROFILE_FILEPATH="Profile_Admin_Page_Object_Repository/AddUserProfile.properties";
	public static final String TESTDATA_FILEPATH="src/test_data/TestData.properties";
	
	public static final String USER_PROFILE_OPTIONS_FILEPATH="Profile_Admin_Page_Object_Repository/User_Profile_Options.properties";
	public static final String ADD_USER_PROFILE_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/AddUserProfileSendkeys.properties";
	public static final String SEARCH_USER_PROFILE_FILEPATH="Profile_Admin_Page_Object_Repository/SearchUserProfile.properties";
	public static final String SEARCH_USER_PROFILE_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/SearchUserProfileSendkeys.properties";
	public static final String MODIFY_MY_PROFILE_FILEPATH="Profile_Admin_Page_Object_Repository/ModifymyProfile.properties";
	public static final String MODIFY_MY_PROFILE_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/ModifymyProfileSendkeys.properties";
	public static final String VALIDATION_PROFILE_FILEPATH="Profile_Admin_Page_Object_Repository/Validation_Profile.properties";
	public static final String ASSIGN_EXTERNAL_REPORT_URL_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/AssignExternalReportURL_Admin.properties";
	public static final String ASSIGN_EXTERNAL_REPORT_URL_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/AssignExternalReportURL_AdminSendkeys.properties";
	public static final String ADMINISTRATION_FILEPATH="Profile_Admin_Page_Object_Repository/Administration.properties";
	public static final String ASSIGN_QUALITY_ADMINISTRATOR_EMAIL_ADDRESS_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/AssignQualityAdministratorEmailAddress_Admin.properties";
	public static final String ASSIGN_QUALITY_ADMINISTRATOR_EMAIL_ADDRESS_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/AssignQualityAdministratorEmailAddress_AdminSendkeys.properties";
	public static final String ASSIGN_REUSE_COORDINATOR_EMAIL_ADDRESS_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/AssignReuseCoordinatorEmailAddress_Admin.properties";
	public static final String ASSIGN_REUSE_COORDINATOR_EMAIL_ADDRESS_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/AssignReuseCoordinatorEmailAddress_AdminSendkeys.properties";
	public static final String VENDOR_EXPEDITE_MANAGEMENT_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/VendorExpediteManagement_Admin.properties";
	public static final String VENDOR_EXPEDITE_MANAGEMENT_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/VendorExpediteManagement_AdminSendkeys.properties";
	public static final String VALIDATION_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/Validation_Admin.properties";
	public static final String VALIDATION_VENDOR_EXPEDITE_MANAGEMENT_FILEPATH="Profile_Admin_Page_Object_Repository/Validation_VendorExpediteManagement_Admin.properties";
	public static final String VALIDATION_VENDOR_CONTACT_MAINTENANCE_FILEPATH="Profile_Admin_Page_Object_Repository/Validation_VendorContactMaintenance_Admin.properties";
	public static final String VENDOR_CONTACT_MAINTENANCE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/VendorContactMaintenance_Admin.properties";
	public static final String VENDOR_CONTACT_MAINTENANCE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/VendorContactMaintenance_AdminSendkeys.properties";
	public static final String DISCREPANCY_MAINTENANCE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/DiscrepancyMaintenance_Admin.properties";
	public static final String DISCREPANCY_ADD_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/DiscrepancyAdd_Admin.properties";
	public static final String DISCREPANCY_MAINTENANCE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/DiscrepancyMaintenance_AdminSendkeys.properties";
	public static final String ORGANISATION_GROUP_MAINTENANCE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/Organization_Group_Maintenance_Admin.properties";
	public static final String ORGANISATION_MAINTENANCE_ADD_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/OrganizationMaintenanceAdd_Admin.properties";
	public static final String ORGANISATION_MAINTENANCE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/OrganizationMaintenance_AdminSendkeys.properties";
	public static final String GROUP_MAINTENANCE_ADD_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/GroupMaintenanceAdd_Admin.properties";
	public static final String GROUP_MAINTENANCE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/GroupMaintenance_AdminSendkeys.properties";
	public static final String LMV_MAINTENANCE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/LMVMaintenance_Admin.properties";
	public static final String LMV_MAINTENANCE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/LMVMaintenance_AdminSendkeys.properties";
	public static final String HOLIDAY_MAINTENANCE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/HolidayMaintenance_Admin.properties";
	public static final String HOLIDAY_MAINTENANCE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/HolidayMaintenance_AdminSendkeys.properties";
	public static final String VALIDATION_SPLASH_PAGE_MAINTENANCE_FILEPATH="Profile_Admin_Page_Object_Repository/Validation_SplashPageMaintenance_Admin.properties";
	public static final String SPLASH_PAGE_MAINTENANCE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/SplashPageMaintenance_Admin.properties";
	public static final String SPLASH_PAGE_MAINTENANCE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/SplashPageMaintenance_AdminSendkeys.properties";
	public static final String VALIDATION_MASS_UPDATE_TOOL_FILEPATH="Profile_Admin_Page_Object_Repository/Validation_MassUpdateTool_Admin.properties";
	public static final String MASS_UPDATE_TOOL_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/MassUpdateTool_Admin.properties";
	public static final String MASS_UPDATE_TOOL_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/MassUpdateTool_AdminSendkeys.properties";
	public static final String MASS_UPDATE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/MassUpdateAdmin_Admin.properties";
	public static final String MASS_UPDATE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/MassUpdateAdmin_AdminSendkeys.properties";
	public static final String LMV_ROUTING_MAINTENANCE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/LMVRoutingMaintenance_Admin.properties";
	public static final String LMV_ROUTING_MAINTENANCE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/LMVRoutingMaintenance_AdminSendkeys.properties";
	public static final String VALIDATION_MATERIAL_STATUS_CHANGE_FILEPATH="Profile_Admin_Page_Object_Repository/Validation_MaterialStatusChange_Admin.properties";
	public static final String MATERIAL_STATUS_CHANGE_ADMIN_FILEPATH="Profile_Admin_Page_Object_Repository/MaterialStatusChange_Admin.properties";
	public static final String MATERIAL_STATUS_CHANGE_ADMIN_SENDKEYS_FILEPATH="Profile_Admin_Page_Object_Repository/MaterialStatusChange_AdminSendkeys.properties";
	
	public static final String Path_TestData = "src/test_data/";
	public static final String File_TestData = "TestData.xlsx";
	

}
